"""empty message

Revision ID: 24af2df68348
Revises: be402ebcda0c
Create Date: 2024-06-29 08:43:44.122164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24af2df68348'
down_revision = 'be402ebcda0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flavor')
    # ### end Alembic commands ###
