"""added image_url field to Recipe Model

Revision ID: e90f509f5f09
Revises: cc9ab729256e
Create Date: 2024-07-09 15:27:13.353517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90f509f5f09'
down_revision = 'cc9ab729256e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('ingredients', sa.TEXT(), nullable=False),
    sa.Column('instructions', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('area', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_recipes_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipe')
    # ### end Alembic commands ###
